<a href="https://colab.research.google.com/github/RasnaDhakal/ML-Algorithms-from-Scratch/blob/main/Simple_Linear_Regression_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [26]:
df=pd.read_csv("/content/drive/MyDrive/DSMP/Machine Learning/1. LiR/placement.csv")
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [27]:

#X=df.iloc[:,0]
#y=df.iloc[:,1]

In [28]:
#X

In [29]:
X=df.iloc[:,0].values
y=df.iloc[:,1].values

In [30]:
X

array([6.89, 5.12, 7.82, 7.42, 6.94, 7.89, 6.73, 6.75, 6.09, 8.31, 5.32,
       6.61, 8.94, 6.93, 7.73, 7.25, 6.84, 5.38, 6.94, 7.48, 7.28, 6.85,
       6.14, 6.19, 6.53, 7.28, 8.31, 5.42, 5.94, 7.15, 7.36, 8.1 , 6.96,
       6.35, 7.34, 6.87, 5.99, 5.9 , 8.62, 7.43, 9.38, 6.89, 5.95, 7.66,
       5.09, 7.87, 6.07, 5.84, 8.63, 8.87, 9.58, 9.26, 8.37, 6.47, 6.86,
       8.2 , 5.84, 6.6 , 6.92, 7.56, 5.61, 5.48, 6.34, 9.16, 7.36, 7.6 ,
       5.11, 6.51, 7.56, 7.3 , 5.79, 7.47, 7.78, 8.44, 6.85, 6.97, 6.94,
       8.99, 6.59, 7.18, 7.63, 6.1 , 5.58, 8.44, 4.26, 4.79, 7.61, 8.09,
       4.73, 6.42, 7.11, 6.22, 7.9 , 6.79, 5.83, 6.63, 7.11, 5.98, 7.69,
       6.61, 7.95, 6.71, 5.13, 7.05, 7.62, 6.66, 6.13, 6.33, 7.76, 7.77,
       8.18, 5.42, 8.58, 6.94, 5.84, 8.35, 9.04, 7.12, 7.4 , 7.39, 5.23,
       6.5 , 5.12, 5.1 , 6.06, 7.33, 5.91, 6.78, 7.93, 7.29, 6.68, 6.37,
       5.84, 6.05, 7.2 , 6.1 , 5.64, 7.14, 7.91, 7.19, 7.91, 6.76, 6.93,
       4.85, 6.17, 5.84, 6.07, 5.66, 7.57, 8.28, 6.

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [33]:
X_train.shape

(160,)

In [34]:
X_train.shape[0]

160

In [37]:
class MyLiR:

  def __init__(self):
    self.m=None
    self.b=None

  def fit(self, X_train,y_train):
    num=0
    den=0

    for i in range(X_train.shape[0]):
      num=num+((X_train[i]-X_train.mean())*(y_train[i]-y_train.mean()))
      den=den+((X_train[i]-X_train.mean())*(X_train[i]-X_train.mean()))
      self.m=num/den
      self.b=y_train.mean()-(self.m*X_train.mean())
      print(self.m)
      print(self.b)

  def predict(self, X_test):
    return self.m*X_test+self.b



In [38]:
lr=MyLiR()
lr.fit(X_train,y_train)

0.8400666389004626
-2.8680758017493027
0.46924606814696196
-0.2760631884680049
0.4735784832135009
-0.3063464990071707
0.4368114508414633
-0.04934724066615104
0.4903032804315722
-0.42325178626166293
0.4839693968140894
-0.3789783356431844
0.48640320794067066
-0.3959905233047918
0.49703213346001257
-0.47028604837714694
0.4719939239065887
-0.2952705284868111
0.4397481783518019
-0.06987478241794864
0.47590917171947894
-0.3226378659959255
0.5163397239276872
-0.6052448990217885
0.521190861769847
-0.6391540493423702
0.529161602582466
-0.6948690294512763
0.5305281218210268
-0.7044209135213642
0.529922374981655
-0.7001867809733322
0.5639383415253931
-0.9379562611161529
0.5716752372889344
-0.9920366789473216
0.5729455718328632
-1.0009162380134748
0.5740242768181008
-1.0084563184412234
0.5814518869758193
-1.0603748492180411
0.5765851988353474
-1.0263570032841516
0.5726511703244137
-0.9988583898695067
0.5674090514441672
-0.9622163065290139
0.5710666030961015
-0.9877823639790559
0.5722783622204375
-

In [39]:
X_train[0]

7.14

In [40]:
X_train.mean()

6.989937500000001

In [41]:
X_test[0]

8.58

In [42]:
print(lr.predict(X_test[0]))

3.891116009744203


In [ ]:
#applied code

In [45]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train.reshape(-1,1),y_train)
LinearRegression

sklearn.linear_model._base.LinearRegression

In [46]:
X_test[0]

8.58

In [47]:
X_test.reshape(1,-1)

array([[8.58, 7.15, 5.88, 6.22, 4.57, 4.79, 5.32, 6.86, 8.35, 6.87, 8.94,
        7.9 , 6.93, 5.91, 7.32, 7.82, 5.09, 7.42, 6.94, 7.73, 6.19, 7.28,
        6.73, 7.2 , 8.21, 6.75, 7.87, 7.6 , 8.63, 5.12, 8.15, 7.36, 8.31,
        6.6 , 6.59, 7.47, 7.93, 6.29, 6.37, 6.47]])

In [48]:
y_test.reshape(1,-1)

array([[4.1 , 3.49, 2.08, 2.33, 1.94, 1.48, 1.86, 3.09, 4.21, 2.87, 3.65,
        4.  , 2.89, 2.6 , 2.99, 3.25, 1.86, 3.67, 2.37, 3.42, 2.48, 3.65,
        2.6 , 2.83, 4.08, 2.56, 3.58, 3.81, 4.09, 2.01, 3.63, 2.92, 3.51,
        1.94, 2.21, 3.34, 3.34, 3.23, 2.01, 2.61]])

In [49]:
lr.predict(X_test[0].reshape(1,-1))

array([3.89111601])

In [51]:
m=lr.coef_
b=lr.intercept_

In [52]:
m*8.58+b #checking with formula

array([3.89111601])